crowdfund/accounts/urls.py
from django.urls import path
from . import views , api
from knox import views as knox_views
from django.views.generic.base import TemplateView



app_name = 'accounts'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('register/', views.RegisterationView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.VerificationView.as_view(), name='activate'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('not-verified/', TemplateView.as_view(template_name='accounts/not_verified.html'), name='not_verified'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('profile/', views.profile, name='profile_page'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('profile/<int:pk>/delete', views.ProfileDeleteView.as_view(), name='profile_delete'),
    path('profile/<int:pk>/projects', views.UserProjects.as_view(), name='user_projects'),
    path('profile/<int:pk>/donations', views.UserDonations.as_view(), name='user_donations'),
    
    
    #APIs
    
    path('api/register/', api.RegisterAPI.as_view(), name='registerapi'),
    path('api/login/', api.LoginAPI.as_view(), name='loginapi'),
    path('api/logout/', knox_views.LogoutView.as_view(), name='logoutapi'),
    path('api/user/', api.UserAPI.as_view()),
    # path('api/logoutall/', knox_views.LogoutAllView.as_view(), name='logoutallapi'),

]

crowdfund/crowdfund/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('projects.urls')),
    # path('api/auth/', include('knox.urls')),
    path('api/', include('projectapi.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'), 
    path('oauth/', include('social_django.urls', namespace='social')),  
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowdfund/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('home/', views.index, name='home'),
    path('add_project/', views.AddProject.as_view(), name='add_project'),
    path('project_list/', views.ProjectList.as_view(), name='project_list'),
    path('project_details/<int:pk>/', views.ProjectDetails.as_view(), name='project_details'),
    path('project_details/<int:pk>/comment', views.LeaveComment.as_view(), name='project_comment'),
    path('project_details/<int:project_pk>/comment/<int:pk>', views.LeaveReply.as_view(), name='project_reply'),
    path('project_details/<int:pk>/cancel', views.ProjectCancel.as_view(), name='project_cancel'),
    path('project_details/<int:pk>/donate/', views.MakeDonation.as_view(), name='make_donation'),
    path('search_projects/', views.ProjectSearch.as_view(), name='search_projects'),
    # path('reports/', views.reports, name='reports'),
    path('report_project/<int:pk>', views.ReportProject.as_view(), name='report_project'),
    path('report_comment/<int:pk>', views.ReportComment.as_view(), name='report_comment'),
    path('project_rate/<int:pk>/', views.RatingView.as_view(), name='project_rate'),
    path('category_projects/<str:category>/', views.CategoryProjects.as_view(), name='category_projects'),
]

crowdfund/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Crowds | {% block title %}{% endblock %}</title>
    {% comment %}
    <link rel="stylesheet" href="{% static 'style.css'%}" />
    {% endcomment %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.6.95/css/materialdesignicons.css"
    />
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    {% block navbar %} {% endblock %} {% block content %} {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </body>
</html>

crowdfund/templates/header.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />

    <title>Title</title>
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

crowdfund/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom border-3 border-secondary rounded-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projects:home' %}">Crowds</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item ">
          <a
            class="nav-link"
            href="{% url 'accounts:profile' request.user.pk %}"
            >Profile</a
          >
        </li>
        <li class="nav-item mx-2">
          <a
            class="nav-link"
            aria-current="page"
            href="{% url 'projects:project_list' %}"
            >All Projects</a
          >
        </li>
        <li class="nav-item mx-2">
          <a class="nav-link" href="{% url 'projects:add_project' %}"
            >Start a project</a
          >
        </li>
        <li class="nav-item mx-4 px-5">
          <form
            class="d-flex"
            action="{% url 'projects:search_projects' %}"
            method="GET"
          >
            <input
              class="form-control me-2"
              type="search"
              name="q"
              placeholder="Search"
              aria-label="Search"
            />
            <div class="btn-group">
             <button class="btn btn-outline-light" type="submit">
              Search
            </button>
            <button type="button" class="btn btn-outline-light dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-dark text-center">
              <li class=" px-4">
                <div class="form-check">
                  <input type="checkbox" name="title" class="form-check-input" id="dropdownCheck1">
                  <label class="form-check-label" for="dropdownCheck1">
                    By Title
                  </label>
                </div>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li class=" px-4">
                <div class="form-check">
                  <input type="checkbox" name="tags" class="form-check-input" id="dropdownCheck2">
                  <label class="form-check-label" for="dropdownCheck2">
                    By Tags
                  </label>
                </div>
              </li>
            </ul>
          </div>
          </form>
        </li>
      </ul>
      <div>
        <a
          class="btn btn-outline-secondary rounded-pill"
          href="{% url 'accounts:logout' %}"
          >Log out</a
        >
      </div>
    </div>
  </div>
</nav>