crowdfund/accounts/urls.py
from django.urls import path
from . import views , api
from knox import views as knox_views
from django.views.generic.base import TemplateView



app_name = 'accounts'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('register/', views.RegisterationView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.VerificationView.as_view(), name='activate'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('not-verified/', TemplateView.as_view(template_name='accounts/not_verified.html'), name='not_verified'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('profile/', views.profile, name='profile_page'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('profile/<int:pk>/delete', views.ProfileDeleteView.as_view(), name='profile_delete'),
    path('profile/<int:pk>/projects', views.UserProjects.as_view(), name='user_projects'),
    path('profile/<int:pk>/donations', views.UserDonations.as_view(), name='user_donations'),
    
    
    #APIs
    
    path('api/register/', api.RegisterAPI.as_view(), name='registerapi'),
    path('api/login/', api.LoginAPI.as_view(), name='loginapi'),
    path('api/logout/', knox_views.LogoutView.as_view(), name='logoutapi'),
    path('api/user/', api.UserAPI.as_view()),
    # path('api/logoutall/', knox_views.LogoutAllView.as_view(), name='logoutallapi'),

]

crowdfund/crowdfund/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('projects.urls')),
    # path('api/auth/', include('knox.urls')),
    path('api/', include('projectapi.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'), 
    path('oauth/', include('social_django.urls', namespace='social')),  
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowdfund/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('home/', views.index, name='home'),
    path('add_project/', views.AddProject.as_view(), name='add_project'),
    path('project_list/', views.ProjectList.as_view(), name='project_list'),
    path('project_details/<int:pk>/', views.ProjectDetails.as_view(), name='project_details'),
    path('project_details/<int:pk>/comment', views.LeaveComment.as_view(), name='project_comment'),
    path('project_details/<int:project_pk>/comment/<int:pk>', views.LeaveReply.as_view(), name='project_reply'),
    path('project_details/<int:pk>/cancel', views.ProjectCancel.as_view(), name='project_cancel'),
    path('project_details/<int:pk>/donate/', views.MakeDonation.as_view(), name='make_donation'),
    path('search_projects/', views.ProjectSearch.as_view(), name='search_projects'),
    # path('reports/', views.reports, name='reports'),
    path('report_project/<int:pk>', views.ReportProject.as_view(), name='report_project'),
    path('report_comment/<int:pk>', views.ReportComment.as_view(), name='report_comment'),
    path('project_rate/<int:pk>/', views.RatingView.as_view(), name='project_rate'),
    path('category_projects/<str:category>/', views.CategoryProjects.as_view(), name='category_projects'),
]

crowdfund/projects/models.py
from django.db import models
from taggit.managers import TaggableManager
from accounts.models import User
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=250)
    details = models.TextField()
    CATEGORY_CHOICES = [
        ('Social', 'Social'),
        ('Political', 'Political'),
        ('Sports', 'Sports'),
        ('Educational', 'Educational'),
    ]
    category = models.CharField(
        max_length=11,
        choices=CATEGORY_CHOICES,
        default='Social',
    )
    images = models.ImageField(_('Project Cover'),null=False, blank=False)
    total_target = models.PositiveIntegerField()
    current = models.PositiveIntegerField(default=0)
    tags = TaggableManager()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    is_featured = models.BooleanField(default=False)
    total_rates = models.IntegerField(default=0)
    avg_rate = models.FloatField(default=0)

    def __str__(self):
        return self.title

    def get_details(self):
        return self.details[:25]

    def can_cancel(self):
        return self.current < (self.total_target * 0.25)

    def target_reached(self):
        return self.current == self.total_target

    def calc_avg_rate(self):
        ratings = Rating.objects.filter(project=self).count()
        print(ratings)
        self.avg_rate = round(self.total_rates / ratings, 1)
        return self.avg_rate


class Image(models.Model):
    project = models.ForeignKey(Project, default=None,related_name='extra_images', on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField( blank=True, null=True)

    def __str__(self):
        return f"id: {self.id}, Project: {self.project}, Image: {self.image.url}"


class Donation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.amount} from {self.user.username} to {self.project.title}"

class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    CATEGORY_CHOICES = [
        ('1', 1),
        ('2', 2),
        ('3', 3),
        ('4', 4),
        ('5', 5),
    ]
    rate = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='1',
    )

    def __str__(self):
        return f"{self.user.username} gave {self.project} {self.rate}/5"

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"user: {self.user.username}, project: {self.project.title}"

class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"user: {self.user.username}"
        
class ReportProject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    REPORT_CHOICES = [
        ('hm', 'Harmful'),
        ('fk', 'Fake'),
        ('il', 'Illegale'),
        ('ab', 'Abuse'),
    ]
    category = models.CharField(
        max_length=2,
        choices=REPORT_CHOICES,
        default='fk',
    )
    report_message = models.TextField()    
    
    def __str__(self):
        return f"Report from user: {self.user.username},on project: {self.project.title}"
    
    
class ReportComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    REPORT_CHOICES = [
        ('hm', 'Harmful'),
        ('fk', 'Fake'),
        ('il', 'Illegale'),
        ('ab', 'Abuse'),
    ]
    category = models.CharField(
        max_length=2,
        choices=REPORT_CHOICES,
        default='fk',
    )
    report_message = models.TextField()
    
    def __str__(self):
        return f"Report from user: {self.user.username},on comment: {self.comment}"    

crowdfund/accounts/forms.py
from django import forms
from django.forms.widgets import NumberInput
from .models import User
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate
from django.utils.translation import gettext_lazy as _


class UserForm(UserCreationForm):

    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    profile_picture = forms.ImageField(required=False)
    phone_number = PhoneNumberField(
    widget=PhoneNumberPrefixWidget(initial='EG'), required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'phone_number', 'profile_picture')


class ProfileUpdateForm(forms.ModelForm):

    phone_number = PhoneNumberField(
    widget=PhoneNumberPrefixWidget(initial='EG'), required=False)
    birth_date = forms.DateField(label="Birth Date", required=False,
     widget=NumberInput(attrs={'type':'date'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'phone_number', 'profile_picture', 'birth_date', 'country', 'facebook')


class LoginForm(AuthenticationForm):

    error_messages = {
        'invalid_login': _("Please enter a correct %(username)s and password"),
        'inactive': _("Please activate the account to sign in"),}

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                try:
                    user_temp = User.objects.get(email=username)
                except:
                    user_temp = None

                if user_temp is not None and user_temp.check_password(password):
                    self.confirm_login_allowed(user_temp)
                else:
                    raise forms.ValidationError(
                        self.error_messages['invalid_login'],
                        code='invalid_login',
                        params={'username': self.username_field.verbose_name},
                    )

        return self.cleaned_data

crowdfund/accounts/views.py
from django.contrib.auth.hashers import check_password
from django.urls import reverse, reverse_lazy
from projects.models import Project, Donation
from .utils import token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib import auth, messages
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.db.models.query_utils import Q
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from .models import User
from .forms import ProfileUpdateForm, UserForm, LoginForm
from django.views import View
from django.views.generic import DetailView, UpdateView, DeleteView, ListView
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget



def landing(request):
    return redirect('accounts:login')


class RegisterationView(View):
    
    def get(self, request):
        form = UserForm()
        return render(request, 'accounts/register.html', {'form': form})

    def post(self, request):
        if request.method == 'POST':
            form = UserForm(request.POST, request.FILES)
            if form.is_valid():
                user = form.save(commit=False)
                user.is_active = False
                user.save()

                uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
                domain = get_current_site(request).domain
                link = reverse('accounts:activate', kwargs={
                    'uidb64': uidb64, 'token': token_generator.make_token(user)})

                activate_url = f'http://{domain}{link}'
                
                email_body = f'Here is your activation link:\n{activate_url}'

                send_mail(
                    'Account Activation Email',
                    email_body,
                    'noreply@semicolon.com',
                    [user.email],
                    fail_silently=False,
                )
                return redirect('accounts:landing')
            else:
                return render(request, 'accounts/register.html', {'form': form})


class VerificationView(View):
    def get(self, request, uidb64, token):
        try:
            id = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=id)

            if not token_generator.check_token(user, token):
                return redirect('accounts:login'+'?message='+'User already activated')

            if user.is_active:
                return redirect('accounts:login')
            user.is_active = True
            user.save()
            return redirect('accounts:login')

        except Exception as ex:
            pass

        return redirect('accounts:login')


class UserLoginView(LoginView):
    template_name = 'accounts/login.html'
    redirect_authenticated_user = True
    form_class = LoginForm


class UserLogoutView(View):
    def get(self, request):
        auth.logout(request)
        return redirect('accounts:login')


def profile(request):
    return redirect('accounts:profile', request.user.pk)


class ProfileView(DetailView):
    model = User
    template_name = 'accounts/user_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_projects = Project.objects.filter(user=context['user']).order_by('-start_time')[:2]
        context['user_projects'] = user_projects
        return context


class ProfileUpdateView(UpdateView):
    model = User
    form_class = ProfileUpdateForm
    template_name = 'accounts/profile_update.html'
    # fields = ('first_name', 'last_name', 'username', 'phone_number', 'profile_picture', 'birth_date', 'country', 'facebook')
    

class ProfileDeleteView(DeleteView):
    model = User
    template_name = 'accounts/profile_delete.html'
    success_url = reverse_lazy('accounts:login')

    def post(self, request, *args, **kwargs):
        form_password = request.POST.get('password')
        user_password = request.user.password
        if check_password(form_password, user_password):
            return self.delete(request, *args, **kwargs)
        messages.error(self.request, 'Incorrect password!')
        return redirect('accounts:profile_delete', self.kwargs['pk'])


class UserProjects(ListView):
    model = Project
    template_name = 'projects/project_list.html'
    def get_queryset(self):
        user = User.objects.get(id=self.kwargs['pk'])
        queryset = self.model.objects.filter(user=user)
        return queryset


class UserDonations(ListView):
    model = Donation
    template_name = 'accounts/user_donations.html'
    def get_queryset(self):
        user = User.objects.get(id=self.kwargs['pk'])
        queryset = self.model.objects.filter(user=user).order_by('-created')
        return queryset


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "accounts/password/password_reset_email.txt"
                    c = {
                    "email":user.email,
                    'domain':'127.0.0.1:8000',
                    'site_name': 'Website',
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "user": user,
                    'token': default_token_generator.make_token(user),
                    'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect ("password_reset_done")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="accounts/password/password_reset.html", context={"form":password_reset_form})

crowdfund/accounts/templates/accounts/login.html
{% extends 'base.html' %}

<!-- <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '{your-app-id}',
      cookie     : true,
      xfbml      : true,
      version    : '{api-version}'
    });
      
    FB.AppEvents.logPageView();   
      
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

   FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
});
</script> -->

{% block title %} Log in {% endblock %}

{% block content %}
 <!-- Bootstrap core JavaScript-->
 <script src="vendor/jquery/jquery.min.js"></script>
 <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<div class="container">
  <br><br><div class="row">
    <div class="col-md-6 p-5 mt-5">
    <br><h1>Crowds</h1>
    <h4>Bring your ideas to life!</h4>
    </div>
      <div class="col-md-5">
        <div class="card mt-5 shadow">
          <div class="card-body">
            <div class="card-title py-2">
              <h1>Log in</h1>
            </div>
              <form action="{% url 'accounts:login' %}" method="post" novalidate>
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <div class="text-center col-12">
                <input class=" btn btn-primary my-2 col-11 p-2" type="submit" value="Log in">
                <!-- <p><strong>-- OR --</strong></p>
                  <a href="{% url 'social:begin' 'facebook' %}" class="btn btn-facebook btn-user btn-block">
                    <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook</a> -->
                </div>
                  <!-- <div id="fb-root"></div> -->
                  <!-- <script async defer crossorigin="anonymous" 
                  src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v12.0&appId=368824831666687&autoLogAppEvents=1" 
                  nonce="9SuCltIM"></script> -->
                  <div class="d-flex justify-content-center">
                    <a href="{% url 'social:begin' 'facebook' %}" class="btn btn-primary">Login with Facebook</a>
                  </div>
                <div class="text-center">
                <p>Forgotten password? <a href="{% url 'accounts:password_reset' %}">Reset</a></p>
                </div>
                <div class=" my-3 text-center">
                <a class="btn btn-success p-2" href="{% url 'accounts:register' %}">Create an account</a>
                </div>
                
              </form>
            </div>
          </div>
        </div>
      </div>
    {% comment %} <div class="col-md-3"></div> {% endcomment %}
  </div>
</div>

{% endblock content %}

crowdfund/accounts/templates/accounts/profile_delete.html
{% extends 'base.html' %}

<!-- page title -->
{% block title %} Delete this account {% endblock %}

<!-- page nav -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

<!-- page content -->
{% block content %}
<div class="container d-flex justify-content-center">
    <div class="col-5">
      <div class="card mt-5 shadow">
        <div class="card-body">
          <div class="card-title py-3">
            {% if request.user.pk == user.pk %}
                <h3>Account deletion confirmation</h3>
                {% if messages %}
                  <div class="mt-2">
                      {% for message in messages %}
                      <h5 class="alert alert-danger">{{ message }}</h5>
                      {% endfor %}
                  </div>
                {% endif %}
                </div>
                    <form class="text-center" action="{% url 'accounts:profile_delete' user.pk %}" method="post" novalidate>
                    {% csrf_token %}
                    <h4>Enter Your password</h4>
                    <div class="my-2 form-group">
                      <input class="form-control" name="password" type="password" id="formpassword">
                    </div>
                    <input class=" btn btn-danger m-4 col-2 p-2" type="submit" value="Confirm">
                    </form>
                </div>
            {% else %}
              <h3 class="alert-danger danger p-5">action not allowed</h3>
            {% endif %}
        </div>
      </div>
    </div>
</div>
{% endblock content %}

crowdfund/accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}

<!-- page title -->
{% block title %} Edit profile {% endblock %}

<!-- page nav -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

<!-- page content -->
{% block content %}
<div class="row">
  <div class="col-2"></div>
    <div class="col-8">
      <div class="card mt-5 shadow">
        <div class="card-body">
          <div class="card-title py-3">
            {% if request.user.pk == user.pk %}
                <h2>Edit your personal information</h2>
                </div>
                    <form action="{% url 'accounts:profile_update' user.pk %}" method="post" enctype='multipart/form-data' novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' %}
                    <div class="text-center col-12">
                    <input class=" btn btn-success m-4 col-2 p-2" type="submit" value="Save">
                    <input class=" btn btn-secondary m-4 col-2 p-2" type="reset" value="Reset">
                    <a href="{% url 'accounts:profile_delete' user.pk %}" class="btn btn-danger m-4 col-2 p-2">Delete Account</a>
                    </div>
                    </form>
                </div>
            {% else %}
              <h3 class="alert-danger danger p-5">action not allowed</h3>
            {% endif %}
        </div>
      </div>
    </div>
  <div class="col-2"></div>
</div>
{% endblock content %}

crowdfund/accounts/templates/accounts/register.html
{% extends 'base.html' %}

<!-- page title -->
{% block title %} Register {% endblock %}

<!-- page content -->
{% block content %}
<div class="d-flex justify-content-center">
  <div class="card my-5 col-5 shadow">
    <div class="card-body">
      <div class="card-title py-3">
        <h1>Sign Up</h1>
      </div>
      <div>
        <form
          class="form"
          action="{% url 'accounts:register' %}"
          method="post"
          enctype="multipart/form-data"
          novalidate
        >
          {% csrf_token %}

          <!-- form variable -->
          {% include 'includes/form.html' %}
          <p class="text-muted small">
            - fields with * are required <br />
            - By clicking Sign Up, you agree to our Terms, Data Policy and
            Cookie Policy. You may receive SMS notifications from us and can opt
            out at any time.
          </p>
          <div class="col-12 text-center">
            <input
              type="submit"
              name="sumbit"
              class="my-2 btn btn-success col-4 p-2"
              value="Sign Up"
            />
            <div class="text-center">
              <p>
                Already have an account?
                <a href="{% url 'accounts:login' %}">Log in</a>
              </p>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

crowdfund/accounts/templates/accounts/user_donations.html
{% extends 'base.html' %}

<!-- page title -->
{% block title %} Projects list {% endblock %}

<!-- page nav -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

<!-- page content -->
{% block content %}
  <div class="container col-6">
    <ol class="list-group list-group-numbered">
      {% for donation in object_list %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Project: <a href="{% url 'projects:project_details' donation.project.pk %}">{{ donation.project }}</a></div>
            <div>amount: {{ donation.amount }}</div>
          </div>
        </li>
      {% empty %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">No donations yet</div>
          </div>
        </li>
      {% endfor %}
    </ol>
  </div>
{% endblock %}

crowdfund/accounts/templates/accounts/user_profile.html
{% extends 'base.html' %}

<!-- page title -->
{% block title %} {{ user.first_name }} {{ user.last_name }} {% endblock %}

<!-- page nav -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

<!-- page content -->
{%block content %}
<div class="row px-2 my-1">
  <div class="col-10 mx-auto">
    <!-- Profile widget -->
    <div class="bg-white shadow rounded overflow-hidden">
      <div class="px-4 pt-0 pb-4 bg-dark">
        <div class="mb-4 media align-items-end profile-header">
          <div class="profile mr-3 text-center">
            <div>
              <img
                src="{{ user.profile_picture.url }}"
                alt="..."
                width="130"
                height="120"
                class="mb-2 border border-3 border-secondary rounded"
              />
            </div>
            <div class="media-body text-white">
              <h4 class="mt-0 mb-0">
                {{ user.first_name }} {{ user.last_name }}
              </h4>
              <p class="small">
                <i class="fa fa-map-marker mr-2"></i> {{ user.country.name }}
              </p>
            </div>
          </div>
          {% if request.user.pk == user.pk %}
          <a
            href="{% url 'accounts:profile_update' user.pk %}"
            class="btn btn-outline-light btn-sm btn-block"
            >Edit profile</a
          >
          {% endif %}
        </div>
      </div>

      <div class="bg-dark px-4 py-2 d-flex justify-content-end text-center">
        <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <a class="text-decoration-none" href="{% url 'accounts:user_projects' user.pk %}">
              <h5 class="text-light font-weight-bold mb-0 d-block">
                {{ user.project_set.count }}
              </h5>
              <small class="text-muted">Projects</small
              >
            </a>
          </li>
          <li class="list-inline-item">
            <a class="text-decoration-none" href="{% url 'accounts:user_donations' user.pk %}">
              <h5 class="text-light font-weight-bold mb-0 d-block">
                {{ user.donation_set.count }}
              </h5>
              <small class="text-muted">Donations</small
              >
            </a>
          </li>
        </ul>
      </div>

      <div class="py-4 px-4">
        <div class="d-flex align-items-center justify-content-between mb-3">
          <h5 class="mb-0">{{ user.first_name }}'s latest projects</h5>
        </div>
        <div class="row d-flex justify-content-center">
          {% for project in user_projects %}
          <div class="card col-4 mx-3 p-2 shadow">
            <a id="project-title" href="{% url 'projects:project_details' project.pk %}">
              <img
                src="{{ project.images.url }}"
                class="card-img-top"
                alt="{{ project.title }}"
              />
            <div class="card-body">
              <h5 class="card-title">{{ project.title }} | {{ project.category }}</h5>
            </a>
              <div>
                {% for tag in project.tags.all %}
                <button
                  type="button"
                  class="btn btn-outline-primary btn-sm"
                  disabled
                >
                  {{ tag }}
                </button>
                {% endfor %}
              </div>
              <p class="card-text">{{ project.details }}</p>
              {% if request.user != user and not project.target_reached %}
                <a href="{% url 'projects:make_donation' project.pk %}" class="btn btn-success">Donate</a>
              {% endif %}
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="py-4">
          <h5 class="mb-3">Recent Comments</h5>
          <div class="list-group">
            {% for comment in user.comment_set.all reversed %}
            <div class="list-group-item">
                <div class="d-flex w-100 justify-content-between">
                    <a href="{% url 'projects:project_details' comment.project.pk %}"><h5 class="mb-1">{{ comment.project }}</h5></a>
                    <div class="dropdown">
                        <a class="link-dark text-decoration-none fw-bolder m-1" href="" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">. . .</a>
                        <ul class="dropdown-menu rounded-3 shadow-lg" aria-labelledby="dropdownMenuButton1">
                            {% if request.user == comment.user %}
                              <li><a class="dropdown-item" href="#">reply</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="#">delete</a></li>
                            {% else %}
                              <li><a class="dropdown-item" href="#">reply</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="{% url 'projects:report_comment' comment.pk %}">report</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <small class="text-muted mb-1">{{ comment.created }}</small>
                <p class="mb-1">{{ comment.comment }}</p>
            </div>
            {% endfor %}
        </div>
        </div>
      </div>
    </div>
    <!-- End profile widget -->
  </div>
</div>
{% endblock %}