crowdfund/accounts/urls.py
from django.urls import path
from . import views , api
from knox import views as knox_views
from django.views.generic.base import TemplateView



app_name = 'accounts'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('register/', views.RegisterationView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.VerificationView.as_view(), name='activate'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('not-verified/', TemplateView.as_view(template_name='accounts/not_verified.html'), name='not_verified'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('profile/', views.profile, name='profile_page'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('profile/<int:pk>/delete', views.ProfileDeleteView.as_view(), name='profile_delete'),
    path('profile/<int:pk>/projects', views.UserProjects.as_view(), name='user_projects'),
    path('profile/<int:pk>/donations', views.UserDonations.as_view(), name='user_donations'),
    
    
    #APIs
    
    path('api/register/', api.RegisterAPI.as_view(), name='registerapi'),
    path('api/login/', api.LoginAPI.as_view(), name='loginapi'),
    path('api/logout/', knox_views.LogoutView.as_view(), name='logoutapi'),
    path('api/user/', api.UserAPI.as_view()),
    # path('api/logoutall/', knox_views.LogoutAllView.as_view(), name='logoutallapi'),

]

crowdfund/crowdfund/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('projects.urls')),
    # path('api/auth/', include('knox.urls')),
    path('api/', include('projectapi.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'), 
    path('oauth/', include('social_django.urls', namespace='social')),  
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowdfund/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('home/', views.index, name='home'),
    path('add_project/', views.AddProject.as_view(), name='add_project'),
    path('project_list/', views.ProjectList.as_view(), name='project_list'),
    path('project_details/<int:pk>/', views.ProjectDetails.as_view(), name='project_details'),
    path('project_details/<int:pk>/comment', views.LeaveComment.as_view(), name='project_comment'),
    path('project_details/<int:project_pk>/comment/<int:pk>', views.LeaveReply.as_view(), name='project_reply'),
    path('project_details/<int:pk>/cancel', views.ProjectCancel.as_view(), name='project_cancel'),
    path('project_details/<int:pk>/donate/', views.MakeDonation.as_view(), name='make_donation'),
    path('search_projects/', views.ProjectSearch.as_view(), name='search_projects'),
    # path('reports/', views.reports, name='reports'),
    path('report_project/<int:pk>', views.ReportProject.as_view(), name='report_project'),
    path('report_comment/<int:pk>', views.ReportComment.as_view(), name='report_comment'),
    path('project_rate/<int:pk>/', views.RatingView.as_view(), name='project_rate'),
    path('category_projects/<str:category>/', views.CategoryProjects.as_view(), name='category_projects'),
]

crowdfund/accounts/models.py
from django.db import models
from django.urls import reverse_lazy
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from django_countries.fields import CountryField



class User(AbstractUser):
    
    email = models.EmailField(_('email address'), unique=True)
    phone_number = PhoneNumberField(null=True, blank=True, unique=True)
    date_joined = models.DateField(auto_now_add=True)
    profile_picture = models.ImageField(default='avatar.png', null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    country = CountryField(null=True, blank=True)
    facebook = models.URLField(max_length=200, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse_lazy('accounts:profile', kwargs={'pk': self.pk})

crowdfund/projects/models.py
from django.db import models
from taggit.managers import TaggableManager
from accounts.models import User
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=250)
    details = models.TextField()
    CATEGORY_CHOICES = [
        ('Social', 'Social'),
        ('Political', 'Political'),
        ('Sports', 'Sports'),
        ('Educational', 'Educational'),
    ]
    category = models.CharField(
        max_length=11,
        choices=CATEGORY_CHOICES,
        default='Social',
    )
    images = models.ImageField(_('Project Cover'),null=False, blank=False)
    total_target = models.PositiveIntegerField()
    current = models.PositiveIntegerField(default=0)
    tags = TaggableManager()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    is_featured = models.BooleanField(default=False)
    total_rates = models.IntegerField(default=0)
    avg_rate = models.FloatField(default=0)

    def __str__(self):
        return self.title

    def get_details(self):
        return self.details[:25]

    def can_cancel(self):
        return self.current < (self.total_target * 0.25)

    def target_reached(self):
        return self.current == self.total_target

    def calc_avg_rate(self):
        ratings = Rating.objects.filter(project=self).count()
        print(ratings)
        self.avg_rate = round(self.total_rates / ratings, 1)
        return self.avg_rate


class Image(models.Model):
    project = models.ForeignKey(Project, default=None,related_name='extra_images', on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField( blank=True, null=True)

    def __str__(self):
        return f"id: {self.id}, Project: {self.project}, Image: {self.image.url}"


class Donation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.amount} from {self.user.username} to {self.project.title}"

class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    CATEGORY_CHOICES = [
        ('1', 1),
        ('2', 2),
        ('3', 3),
        ('4', 4),
        ('5', 5),
    ]
    rate = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default='1',
    )

    def __str__(self):
        return f"{self.user.username} gave {self.project} {self.rate}/5"

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"user: {self.user.username}, project: {self.project.title}"

class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"user: {self.user.username}"
        
class ReportProject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    REPORT_CHOICES = [
        ('hm', 'Harmful'),
        ('fk', 'Fake'),
        ('il', 'Illegale'),
        ('ab', 'Abuse'),
    ]
    category = models.CharField(
        max_length=2,
        choices=REPORT_CHOICES,
        default='fk',
    )
    report_message = models.TextField()    
    
    def __str__(self):
        return f"Report from user: {self.user.username},on project: {self.project.title}"
    
    
class ReportComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    REPORT_CHOICES = [
        ('hm', 'Harmful'),
        ('fk', 'Fake'),
        ('il', 'Illegale'),
        ('ab', 'Abuse'),
    ]
    category = models.CharField(
        max_length=2,
        choices=REPORT_CHOICES,
        default='fk',
    )
    report_message = models.TextField()
    
    def __str__(self):
        return f"Report from user: {self.user.username},on comment: {self.comment}"    

crowdfund/projects/forms.py
from typing import ValuesView
from django import forms 
from .models import Project, Donation, ReportComment, ReportProject
from django.forms.widgets import NumberInput
from django.forms.models import inlineformset_factory

class AddProjectForm(forms.ModelForm):
    
    start_time = forms.DateField(label="Start Date", required=True,
     widget=NumberInput(attrs={'type':'date'}))

    end_time = forms.DateField(label="End Date", required=True,
     widget=NumberInput(attrs={'type':'date'}))

    class Meta:
        model = Project
        fields = '__all__'
        exclude = ('user', 'current', 'is_featured', 'avg_rate')


class MakeDonationForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = ['amount']


# class MakeReportForm(forms.ModelForm):
#     class Meta:
#         models = (ReportProject, ReportComment)
#         fields = ['category', 'report_message']
        
# class ImageForm(forms.ModelForm):

#     image = forms.ImageField(label='Images')
#     class Meta:
#         model = Images
#         fields = ('image', )

crowdfund/projects/templates/projects/add_project.html
{% extends 'base.html' %}

<!-- page title -->
{% block title %} Add Project {% endblock %}

<!-- page nav -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

<!-- page content -->
{% block content %}
<div class="d-flex justify-content-center">
  <div class="card my-5 col-5 shadow">
    <div class="card-body">
      <div class="card-title py-3">
        <h1>Start a project</h1>
      </div>
      <div>
        <form
          class="form"
          action="{% url 'projects:add_project' %}"
          method="post"
          enctype="multipart/form-data"
          novalidate
        >
          {% csrf_token %}

          <!-- form variable -->

           {% include 'includes/form.html' %} 
           {% comment %} <input required name="images" type="file" multiple class="form-control-file"/> {% endcomment %}
           <div class="my-2">
            <label for="formFileMultiple" class="form-label">(Optional) Add More Images:</label>
            <input class="form-control" name="images" type="file" id="formFileMultiple" multiple>
          </div>
          <p class="text-muted small">- fields with * are required <br /></p>
          <div class="col-12 text-center">
            <input
              type="submit"
              name="sumbit"
              class="my-2 btn btn-success col-4 p-2"
              value="Create Project"
            />
            <div class="text-center"></div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

crowdfund/projects/templates/projects/comment_report_form.html
{% extends 'base.html'%}


<!-- page title -->
{% block title %} Comment Report {% endblock %}

<!-- page nav -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="card my-5 col-5 shadow">
      <div class="card-body">
        <div class="card-title py-3">
          <h1>Report this comment</h1>
        </div>
        <div>
            <form method="post" action="{% url 'projects:report_comment' comment.pk %}" novalidate>
                {% csrf_token %}
                {% include 'includes/form.html'%}
                <br>
                <div class="d-flex justify-content-center" >
                
                <input class="btn btn-danger ms-1" type="submit" value="Report">
                <a href="{% url 'projects:project_details' comment.project.pk %}" class="btn btn-primary ms-5" type="submit">Cancel</a>
             
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
    
{% endblock %}

crowdfund/projects/templates/projects/delete_comment.html
<form method="POST" action="{% url 'projects:delete_comment' comment.pk %}">
  {% csrf_token %}<input type="submit" value="DELETE">
</form>

crowdfund/projects/templates/projects/project_cancel.html
{% extends 'base.html' %}

<!-- page title -->
{% block title %} Cancel this fund {% endblock %}

<!-- page nav -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

<!-- page content -->
{% block content %}
<div class="row">
  <div class="col-2"></div>
    <div class="col-8">
      <div class="card mt-5 shadow">
        <div class="card-body">
          <div class="card-title py-3">
            {% if request.user.pk == object.user.pk %}
                <h2>Abort Fund</h2>
                {% if object.can_cancel %}
                    </div>
                        <form action="{% url 'projects:project_cancel' object.pk %}" method="post" novalidate>
                        {% csrf_token %}
                        <p class="alert alert-danger" role="alert">
                            Are you sure you want to cancel this project
                        </p>
                        <input class=" btn btn-danger m-4 col-2 p-2" type="submit" value="Confirm">
                        </form>
                    </div>
                {% else %}
                    <p class="alert alert-info" role="alert">
                        Can't cancel this project <br>
                        - current fund has exceeded 25% of the target
                    </p>
                    <a href="{% url 'projects:project_details' object.pk %}" class=" btn btn-secondary m-4 col-2 p-2">Back to project</a>
                {% endif %}
            {% else %}
                <h3 class="alert-danger danger p-5">action not allowed</h3>
            {% endif %}
        </div>
      </div>
    </div>
  <div class="col-2"></div>
</div>
{% endblock content %}

crowdfund/projects/templates/projects/project_detail.html
{% extends 'base.html' %}

<!-- page title -->
{% block title %} {{ project.title }} {% endblock %}

<!-- page nav -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

<!-- page content -->
{% block content %}
<div class="container d-flex justify-content-center">
    <div class="card p-3 m-2 col-6 shadow">

        <div class="d-flex justify-content-between">
            <h3>{{ project.title }} | {{ project.category }}</h3>
            <div class="dropdown">
              <a class="link-dark text-decoration-none fw-bolder m-1" href="" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">. . .</a>
              <ul class="dropdown-menu rounded-3 shadow-lg" aria-labelledby="dropdownMenuButton1">
                {% if request.user == project.user %}
                <li><a class="dropdown-item" href="{% url 'projects:project_cancel' project.pk %}">cancel project</a></li>
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'accounts:profile' project.user.pk %}">owner profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'projects:project_rate' project.pk %}">Rate</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">report</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        <div>
            {% for tag in project.tags.all %}
            <button
            type="button"
            class="btn btn-outline-primary btn-sm"
              disabled
              >
              {{ tag }}
            </button>
            {% endfor %}
          </div>
          <br>
          <div id="images-carousel" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner bg-dark text-center">
                <div class="carousel-item active">
                  <img src="{{project.images.url}}" class="testi-overly d-block w-100" alt="sliderImg">
                </div>
                {% for image in images %}
                    <div class="carousel-item">
                        <img src="{{image.image.url}}" class="testi-overly d-block w-100" alt="sliderImg">
                        </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#images-carousel" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#images-carousel" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
        </div>
        <p><B>{{ project.details }}</B></p>
        <div >
        {% if project.avg_rate > 4.4 %}
        <i class="fa fa-star checked " style="float: left;"></i>
        <i class="fa fa-star  checked " style="float: left;"></i>
        <i class="fa fa-star checked  " style="float: left;"></i>
        <i class="fa fa-star checked " style="float: left;"></i>
        <i class="fa fa-star  checked " style="float: left;"></i>
        {% elif project.avg_rate > 3.4 %}
        <i class="fa fa-star checked " style="float: left;"></i>
        <i class="fa fa-star  checked " style="float: left;"></i>
        <i class="fa fa-star  checked " style="float: left;"></i>
        <i class="fa fa-star  checked" style="float: left;"></i>
        <i class="fa fa-star   " style="float: left;"></i>
        {% elif project.avg_rate > 2.4 %}
        <i class="fa fa-star checked " style="float: left;"></i>
        <i class="fa fa-star  checked " style="float: left;"></i>
        <i class="fa fa-star  checked " style="float: left;"></i>
        <i class="fa fa-star" style="float: left;"></i>
        <i class="fa fa-star" style="float: left;"></i>
        {% elif project.avg_rate > 1.4 %}
        <i class="fa fa-star checked " style="float: left;"></i>
        <i class="fa fa-star  checked " style="float: left;"></i>
        <i class="fa fa-star   " style="float: left;"></i>
        <i class="fa fa-star  " style="float: left;"></i>
        <i class="fa fa-star   " style="float: left;"></i>
        {% elif project.avg_rate > 0.4 %}
        <i class="fa fa-star checked " style="float: left;"></i>
        <i class="fa fa-star   " style="float: left;"></i>
        <i class="fa fa-star   " style="float: left;"></i>
        <i class="fa fa-star  " style="float: left;"></i>
        <i class="fa fa-star   " style="float: left;"></i>
        {% endif %}
    </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Target</th>
                    <th>Current</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ project.total_target }} EGP</td>
                    <td>{{ project.current }} EGP</td>
                </tr>
            </tbody>
        </table>
        <table class="table">
            <thead>
                <tr>
                    <th>Doner</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                {% for donation in project.donation_set.all %}
                <tr>
                    <td><a href="{% url 'accounts:profile' donation.user.pk %}">{{ donation.user.username }}</a></td>
                    <td>{{ donation.amount }} EGP</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if not project.target_reached and project.user != request.user %}
            <div class="text-center">
                <a class="btn btn-success btn-lg col-8" href="{% url 'projects:make_donation' project.pk %}">Make a donation</a>
            </div>
        {% endif %}
    </div>
    <div class="card p-3 col-6 m-2 shadow">
        <form class="form" action="{% url 'projects:project_comment' project.pk %}" method="post">
            {% csrf_token %}
            <div class="mb-3 justify-content-end">
                <input type="text" name="comment" class="form-control" placeholder="Leave a comment here">
                <input class=" my-1 btn btn-primary" type="submit" value="Comment">
            </div>
        </form>
        <div class="list-group">
            {% for comment in project.comment_set.all reversed %}
            <div class="list-group-item">
                <div class="d-flex w-100 justify-content-between">
                    <a href="{% url 'accounts:profile' comment.user.pk %}"><h5 class="mb-1">{{ comment.user.username }}</h5></a>
                    <div class="dropdown">
                        <a class="link-dark text-decoration-none fw-bolder m-1" href="" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">. . .</a>
                        <ul class="dropdown-menu rounded-3 shadow-lg" aria-labelledby="dropdownMenuButton1">
                            {% if request.user == comment.user %}
                              <li><a class="dropdown-item" href="{% url 'projects:project_reply' project.pk comment.pk%}">reply</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="#">delete</a></li>
                            {% else %}
                              <li><a class="dropdown-item" href="{% url 'projects:project_reply' project.pk comment.pk%}">reply</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="{% url 'projects:report_comment' comment.pk %}">report</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <small class="text-muted mb-1">{{ comment.created }}</small>
                <p class="mb-1">{{ comment.comment }}</p>
              
                <div class="list-group">
                    {% for reply in comment.reply_set.all reversed %}
                    
                    <div class="list-group-item" >
                        <div class="d-flex w-100 justify-content-between">
                            <a href="{% url 'accounts:profile' reply.user.pk %}"><h5 class="mb-1">{{ reply.user.username }}</h5></a>
                            {% comment %} {% if request.user != reply.user %}
                            <div class="dropdown">
                                <a class="link-dark text-decoration-none fw-bolder m-1" href="" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">. . .</a>
                                <ul class="dropdown-menu rounded-3 shadow-lg" aria-labelledby="dropdownMenuButton1">
                                      <li><a class="dropdown-item" href="{% url 'projects:report_comment' reply.pk %}">report</a></li>
                                </ul>
                            </div>
                            {% endif %} {% endcomment %}
                            <small class="text-muted mb-1">{{ reply.created }}</small>
                        </div>
                        <p class="mb-1">{{reply.reply }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
            
            {% endfor %}
        </div>

    </div>
</div>
<div class="container">
    <div class="row"><h2>Similar Projects</h2></div>
    <div class="row">
        {% for project in similar_projects %}
            {% if request.user != project.user %}
            <div class="card p-1 col-4 shadow">
                <img src="{{ project.images.url }}" />
                <div class="d-flex justify-content-between">
                    <h5>{{ project.title }} | {{ project.category }}</h5>
                    <div class="dropdown">
                    <a class="link-dark text-decoration-none fw-bolder m-1" href="" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">. . .</a>
                    <ul class="dropdown-menu rounded-3 shadow-lg" aria-labelledby="dropdownMenuButton1">

                        {% if user.pk in rating.user_set.all%}
                        <li><a class="dropdown-item" href="{% url 'projects:make_donation' project.pk %}">Donate</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:profile' project.user.pk %}">Owner profile</a></li>
                        {%else%}
                        <li><a class="dropdown-item" href="{% url 'projects:make_donation' project.pk %}">Donate</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:profile' project.user.pk %}">Owner profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'projects:project_rate' project.pk %}">Rate</a></li>
                        <li><a class="dropdown-item" href="{% url 'projects:report_project' project.pk %}">Report</a></li>

                        <li><hr class="dropdown-divider"></li>
                        {% endif %}
                        
                    </ul>
                    </div>
                </div>
                <div>
                    {% for tag in project.tags.all %}
                    <button
                    type="button"
                    class="btn btn-outline-primary btn-sm"
                    disabled
                    >
                    {{ tag }}
                    </button>
                    {% endfor %}
                </div>
                <hp>{{ project.get_details }}... <a class="link-dark" href="{% url 'projects:project_details' project.pk %}">see more</a></hp>
                </div>
            {% endif %}
        {% empty %}
            <h4>No similar projects.</h4>
        {% endfor %}
    </div>
</div>
<style>
    .checked{
    color: orange;
  }
  </style>
{% endblock %}

crowdfund/projects/templates/projects/project_list.html
{% extends 'base.html' %}

<!-- page title -->
{% block title %} Projects list {% endblock %}

<!-- page nav -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

<!-- page content -->
<div class="container d-flex justify-content-around">
</div>
{% block content %}
  <div class="container-fluid">
      <div class="row">
        {% for project in object_list %}
          {% if not project.target_reached %}
            <div class="card p-1 col-3 shadow">
              <img src="{{ project.images.url }}" />
              <div class="d-flex justify-content-between">
                <h5>{{ project.title }} | {{ project.category }}</h5>
                <div class="dropdown">
                  <a class="link-dark text-decoration-none fw-bolder m-1" href="" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">. . .</a>
                  <ul class="dropdown-menu rounded-3 shadow-lg" aria-labelledby="dropdownMenuButton1">
                    {% if request.user == project.user %}
                      <li><a class="dropdown-item" href="{% url 'projects:project_cancel' project.pk %}">cancel project</a></li>
                    {% else %}
                      <li><a class="dropdown-item" href="{% url 'projects:make_donation' project.pk %}">Donate</a></li>
                      <li><a class="dropdown-item" href="{% url 'accounts:profile' project.user.pk %}">Owner profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'projects:project_rate' project.pk %}">Rate</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'projects:report_project' project.pk %}">Report</a></li>
                    {% endif %}
                  </ul>
                </div>
              </div>
              <div>
                {% for tag in project.tags.all %}
                <button
                type="button"
                class="btn btn-outline-primary btn-sm"
                  disabled
                  >
                  {{ tag }}
                </button>
                {% endfor %}
              </div>
              <hp>{{ project.get_details }}... <a class="link-dark" href="{% url 'projects:project_details' project.pk %}">see more</a></hp>
            </div>
          {% endif %}
        {% empty %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">No projects yet</div>
          </div>
        </li>
        {% endfor %}
      </div>
  </div>
{% endblock %}

crowdfund/projects/templates/projects/project_report_form.html
{% extends 'base.html'%}


<!-- page title -->
{% block title %} Project Report {% endblock %}

<!-- page nav -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="card my-5 col-5 shadow">
      <div class="card-body">
        <div class="card-title py-3">
          <h1>Report this project</h1>
        </div>
        <div>
            <form method="post" action="{% url 'projects:report_project' project_pk %}" novalidate>
                {% csrf_token %}
                {% include 'includes/form.html'%}
                <br>
                <div class="d-flex justify-content-center" >
                
                <input class="btn btn-danger ms-1" type="submit" value="Report">
                <a href="{% url 'projects:project_details' project_pk %}" class="btn btn-primary ms-5" type="submit">Cansel</a>
             
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
    
{% endblock %}